Source Code/Flask/app/models.py
from . import db

class Credentials(db.Model):
	"""username and password for system"""
	__tablename__ = "credentials"
	password = db.Column(db.String(20))
	username = db.Column(db.String(20), primary_key=True)

Source Code/Flask/app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField
from wtforms.validators import Required

class NameForm(FlaskForm):
	"""Class for configuring login form"""
	name = StringField('Username* :', validators=[Required()])
	password = PasswordField('Password* :', validators=[Required()])
	submit = SubmitField('Submit')

class ChangeCredentials(FlaskForm):
	"""Class for configuring change credentials form"""
	new_name = StringField('New Username :')
	old_pass = PasswordField('Old Password* :', validators=[Required()])
	new_pass = PasswordField('New Password* :', validators=[Required()])
	submit = SubmitField('Update')

Source Code/Flask/app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from config import config

bootstrap = Bootstrap()
db = SQLAlchemy()

def create_app(config_name):
	app = Flask(__name__)
	app.config.from_object(config[config_name])

	# Load development configurations, bootstrap and database configurations
	config[config_name].init_app(app)
	bootstrap.init_app(app)
	db.init_app(app)

	from .main import main
	app.register_blueprint(main)
	return app

Source Code/Flask/app/main/__init__.py
# Organizing application into distinct components.
from flask import Blueprint

main = Blueprint("main", __name__)

from . import views, errors

Source Code/Flask/app/main/views.py
from flask import render_template, session, redirect, url_for, flash, request
from . import main
from .. import db
from ..models import Credentials
from .forms import NameForm, ChangeCredentials
import requests, json
import logging, sys, os, socket

@main.route("/", methods=['GET', 'POST'])
def index():
	name = None
	form = NameForm()

	param = request.args.get("redirect")
	if param == "True":
		session["name"] = False
		redirect(url_for("main.index"))

	if form.validate_on_submit():
		credential_query = Credentials.query.filter_by(username=form.name.data, password=form.password.data)
		credential = credential_query.first()
		credential_count = credential_query.count()

		if credential_count != 1:
			flash("Credentials Incorrect. Access denied.","error")
			return render_template("index.html", form=form, name=session.get("name")), 200					

		session["name"] = form.name.data
		form.name.data = ""
		flash("Succesfully logged in.", "success")
		redirect(url_for("main.index"))
	return render_template("index.html", form=form, name=session.get("name")), 200

@main.route("/devices", methods=['GET', 'POST'])
def devices():
	resp = requests.get("http://localhost:8082/web/jsonrest/host_tracker/devices")

	# [ 'Logging functionality' ]
	# logger = logging.getLogger(__name__)
	# logger.setLevel(logging.DEBUG)
	# root = logging.getLogger()
	# root.setLevel(logging.DEBUG)
	
	# ch = logging.StreamHandler(sys.stdout)
	# ch.setLevel(logging.DEBUG)
	# formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
	# ch.setFormatter(formatter)
	# root.addHandler(ch)
	# logger.info()

	return render_template("devices.html", resp=resp.json(), name=session.get("name")), 200

@main.route("/switches", methods=['GET'])
def switches():
	resp = requests.get("http://localhost:8082/web/jsonrest/of/switches")
	return render_template("switches.html", resp=resp.json(), name=session.get("name")), 200

@main.route("/links", methods=['GET'])
def links():
	links_rest = requests.get("http://localhost:8082/web/jsonrest/discovery/links")
	switches_rest = requests.get("http://localhost:8082/web/jsonrest/of/switches")
	devices_rest = requests.get("http://localhost:8082/web/jsonrest/host_tracker/devices")
	
	links_json = links_rest.json()
	switches_json = switches_rest.json()
	devices_json = devices_rest.json()

	json_data = {"nodes":[], "links":[]}
	for switch in switches_json:
		data = {}
		data["group"] = "1"
		data["id"] = switch["dpid"]
		json_data["nodes"].append(data)

	for devices in devices_json:
		data = {}
		data["group"] = "2"
		data["id"] = devices["networkAddresses"]
		json_data["nodes"].append(data)

		link = {}
		link["target"] = devices["networkAddresses"]
		link["source"] = devices["switch_dpid"]
		link["value"] = "2"
		json_data["links"].append(link)

	for links in links_json:
		data = {}
		data["target"] = links["dataLayerDestination"]
		data["source"] = links["dataLayerSource"]
		data["value"] = "1"
		json_data["links"].append(data)

	with open("app/static/json/topo.json", 'w') as outfile:
		json.dump(json_data, outfile)
		
	return render_template("links.html", json_data=json_data, name=session.get("name")), 200

@main.route("/credentials", methods=['GET', 'POST'])
def credentials():
	form = ChangeCredentials()
	nameform = NameForm()
	if form.validate_on_submit():
		new_name = form.new_name.data
		new_pass = form.new_pass.data
		old_pass = form.old_pass.data

		credential_query = Credentials.query.filter_by(password=old_pass)
		if credential_query.count() == 1:
			credential = credential_query.first()
			credential.password = new_pass
			if new_name != "":
				credential.username = new_name
				session["name"] = new_name
				flash("Credentials changed successfully.","success")
			else:
				flash("Credentials changed successfully without changing username.","success")

			redirect(url_for("main.index"))
			return render_template("index.html", form=nameform, name=session.get("name")), 200
		else:
			flash("Incorrect old password. Access denied.","error")
			redirect(url_for("main.credentials"))

	return render_template("credentials.html", form=form, name=session.get("name")), 200

@main.route("/ddos", methods=['GET', 'POST'])
def ddos():
	if request.method == "POST":
		fw = open("app/static/json/attack_topo.json","w")
		fw.close()
		
	if os.stat("app/static/json/attack_topo.json").st_size == 0:
		return render_template("ddos.html", flag=False, name=session.get("name")), 200
	else:
		return render_template("ddos.html", flag=True, name=session.get("name")), 200

Source Code/Flask/app/templates/base.html
{% block doc %}
<!DOCTYPE html>
<html>
{% block html %}
<head>
	{% block head %}
		{% block meta %}
			<meta name="viewport" content="width=device-width, initial-scale=1.0">
		{% endblock %}

		<title>{% block title %}{% endblock %}</title>

		{% block styles %}
			<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/bootstrap.min.css')}}">
			<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/style.css')}}">
		{% endblock %}
	{% endblock %}
</head>
<body>
{% block body %}
	{% block navbar %}

	{% endblock %}

	{% block content %}

	{% endblock %}

	{% block scripts %}
		<script type="text/javascript" src="{{url_for('static', filename='js/jquery.min.js')}}"></script>
		<script type="text/javascript" src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>		
	{% endblock %}
{% endblock %}
</body>
{% endblock %}
</html>
{% endblock %}

Source Code/Flask/app/templates/credentials.html
{% extends "header.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
Change Credentials
{% endblock %}

{% block page_content %}
<div class="page-header">
	<h3 class="h3">
		Change Credentials
	</h3>
</div>

<div class="container">
	{{ wtf.quick_form(form) }}
</div>
{% endblock %}

Source Code/Flask/app/templates/ddos.html
{% extends "header.html" %}

{% block title %}
	DDoS Attack Location
{% endblock %}

{% block page_content %}
	<div class="page-header">
		<h3 class="h3">
			DDoS Attack Location
		</h3>
	</div>
	{% if flag == True %}
		<div class="container svg-block">
			<button class="btn btn-success custom-btn">Clear Notification</button>
			<br/><br/>
			<svg width="960" height="500"></svg>
		</div>
	{% else %}
		<div class="container">
			<h4 class="h4">
				Network is not yet under attack.
			</h4>
		</div>
	{% endif %}
{% endblock %}

{% block scripts %}
	{{ super() }}
	<script type="text/javascript" src="{{url_for('static', filename='js/ddos.js')}}"></script>
	<script type="text/javascript" src="{{url_for('static', filename='js/d3.min.js')}}"></script>

	<script type="text/javascript">
		$(".custom-btn").click(function(event) {
			$.ajax({
				url:"{{url_for('main.ddos')}}",
				type: 'POST',
				contentType: 'application/json;charset=UTF-8',
			});	
			location.reload(true);
		});
	</script>

	{% if flag == True %}
	<script type="text/javascript">
		var svg = d3.select("svg");
		var width = +svg.attr("width");
		var height = +svg.attr("height");

		var color = d3.scaleOrdinal()
  							.domain(["1", "2", "3"])
							.range(["#65C400" , "#2290EE", "#000000"]);

		var simulation = d3.forceSimulation().force("link", d3.forceLink().id(function(d) { return d.id; }).distance(60)).force("charge", d3.forceManyBody()).force("center", d3.forceCenter(width / 2, height / 2));

		d3.json("{{url_for('static', filename='json/attack_topo.json')}}", function(error, graph) { 
		if (error) throw error;

		var link = svg.append("g")
					.attr("class", "links")
					.selectAll("line")
					.data(graph.links)
					.enter()
					.append("line")
					.attr("stroke-width", function(d) { 
						return Math.sqrt(d.value); 
					});

		var node = svg.append("g")
					.attr("class", "nodes")
					.selectAll("circle")
					.data(graph.nodes)
					.enter()
					.append("circle")
					.attr("r", 7)
					.attr("fill", function(d) { 
						return color(d.group); 
					})
					.on('dblclick', function(event) {
						connectedNodes(d3.select(this).node().__data__)
					})
					.call(d3.drag()
							.on("start", dragstarted)
							.on("drag", dragged)
							.on("end", dragended)					
					); 

		node.append("title")
			.text(function(d) { 
				return d.id; 
			});

		simulation.nodes(graph.nodes).on("tick", ticked);

		simulation.force("link").links(graph.links);

		function ticked() {
			link.attr("x1", function(d) { 
				return d.source.x; 
			}).attr("y1", function(d) { 
				return d.source.y; 
			}).attr("x2", function(d) { 
				return d.target.x; 
			}).attr("y2", function(d) { 
				return d.target.y; 
			});

			node.attr("cx", function(d) { 
				return d.x; 
			}).attr("cy", function(d) { 
				return d.y; 
			});
		}
		var padding = 1, radius=6;
		function collide(alpha) {
			var quadtree = d3.geom.quadtree(graph.nodes);
			return function(d) {
		    var rb = 2*radius + padding,
		        nx1 = d.x - rb,
		        nx2 = d.x + rb,
		        ny1 = d.y - rb,
		        ny2 = d.y + rb;
		    quadtree.visit(function(quad, x1, y1, x2, y2) {
			if (quad.point && (quad.point !== d)) {
				var x = d.x - quad.point.x,
				y = d.y - quad.point.y,
				l = Math.sqrt(x * x + y * y);
				if (l < rb) {
					l = (l - rb) / l * alpha;
					d.x -= x *= l;
					d.y -= y *= l;
					quad.point.x += x;
					quad.point.y += y;
				}
			}
			return x1 > nx2 || x2 < nx1 || y1 > ny2 || y2 < ny1;
			});
			};
		}
		
		var toggle = 0;
		var linkedByIndex = {};
		for (i = 0; i < graph.nodes.length; i++) {
		    linkedByIndex[i + "," + i] = 1;
		};
		graph.links.forEach(function (d) {
		    linkedByIndex[d.source.index + "," + d.target.index] = 1;
		});
		function neighboring(a, b) {
		    return linkedByIndex[a.index + "," + b.index];
		}
		function connectedNodes(d) {
		    if (toggle == 0) {
		        node.style("opacity", function (o) {
		            return neighboring(d, o) | neighboring(o, d) ? 1 : 0.1;
		        });
		        link.style("opacity", function (o) {
		            return d.index==o.source.index | d.index==o.target.index ? 1 : 0.1;
		        });
		        toggle = 1;
		    } 
		    else {
		        node.style("opacity", 1);
		        link.style("opacity", 1);
		        toggle = 0;
		    }
		}

		force.on("tick", function () {
		    link.attr("x1", function (d) {
		        return d.source.x;
		    }).attr("y1", function (d) {
		        return d.source.y;
		    }).attr("x2", function (d) {
		        return d.target.x;
		    }).attr("y2", function (d) {
		        return d.target.y;
		    });
		    node.attr("cx", function (d) {
		        return d.x;
		    }).attr("cy", function (d) {
		        return d.y;
		    });
		    node.each(collide(0.5));
		});

		});

		function dragstarted(d) {
			if (!d3.event.active) simulation.alphaTarget(0.3).restart();
			d.fx = d.x;
			d.fy = d.y;
		}

		function dragged(d) {
			d.fx = d3.event.x;
			d.fy = d3.event.y;
		}

		function dragended(d) {
			if (!d3.event.active) simulation.alphaTarget(0);
			d.fx = null;
			d.fy = null;
		}
	</script>
	{% endif %}
{% endblock %}

Source Code/Flask/app/templates/devices.html
{% extends "header.html" %}

{% block title %}
	Devices
{% endblock %}

{% block page_content %}
	<div class="page-header">
		<h3 class="h3">
			List of Devices connected : 
		</h3>
	</div>
	<div class="table-responsive">
		<table class="table table-hover">
			{% if resp %}
				{% for line_count in range(resp.__len__()) %}
				<tr>
					<td class="click-dropdown-field">
						<div class="header">
							<strong>
								<span class="device-number">
									Device {{line_count + 1}} :
								</span>

								<span class="device-address">
									{% set network_addr = resp[line_count].networkAddresses.split(" ") %}
									{% if network_addr[0] == "0.0.0.0" %}
										Network Address : {{network_addr[1]}}
									{% else %}
										Network Address : {{network_addr[0]}}
									{% endif %}
								</span>
							</strong>
						</div>

						<div class="content">
							Switch Datapath Id : {{resp[line_count].switch_dpid}}
							<br/>
							Hardware Address : {{resp[line_count].dataLayerAddress}}
							<br/>
							Port Number : {{resp[line_count].port}}
						</div>
					</td>
				</tr>
				{% endfor %}
			{% endif %}
		</table>
	</div>
	{{data}}
{% endblock %}

{% block scripts %}
	{{ super() }}
	<script type="text/javascript" src="{{url_for('static', filename='js/devices.js')}}"></script>
	<script type="text/javascript">
		setInterval(function(){
			$('.table-responsive').load(document.URL +  ' .table-responsive');
		}, 5000);
	</script>
{% endblock %}

Source Code/Flask/app/templates/header.html
{% extends "base.html" %}

{% block head %}
{{ super() }}
<link rel="shortcut-icon" type="image/x-icon" href="{{url_for('static', filename='images/image.ico')}}">
<link rel="icon" type="image/x-icon" href="{{url_for('static', filename='images/image.ico')}}">
{% endblock %}

{% block title %}Midnight Inventers{% endblock %}

{% block navbar %}
<nav class="navbar navbar-inverse">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false">
				<span class="sr-only">Toggle Navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{{url_for('main.index', _external=True)}}">
				<strong>
					Midnight Inventers	
				</strong>
			</a>
		</div>

		{% if name %}
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li>
						<a href="{{url_for('main.devices', _external=True)}}">
							Devices
						</a>
					</li>
					<li>
						<a href="{{url_for('main.switches', _external=True)}}">
							Switches
						</a>
					</li>
					<li>
						<a href="{{url_for('main.links', _external=True)}}">
							Links
						</a>
					</li>
					<li>
						<a href="{{url_for('main.ddos', _external=True)}}">
							DDoS Location
						</a>
					</li>
				</ul>

				<ul class="nav navbar-nav navbar-right">
					<li>
						<a href="{{url_for('main.credentials')}}">
							Change Credentials
						</a>
					</li>
					<li>
						<a href="{{url_for('main.index', redirect=True)}}">
							<span class="glyphicon glyphicon-log-out"></span>
							Logout
						</a>
					</li>
				</ul>
			</div>
		{% endif %}

	</div>
</nav>
{% endblock %}


{% block content %}
<div class="container">
	{% for category, message in get_flashed_messages(with_categories=true) %}
		{% if category == "success" %}
			<div class="alert alert-success">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				<strong>{{ message }}</strong>
			</div>
		{% else %}
			<div class="alert alert-danger">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				<strong>{{ message }}</strong>
			</div>
		{% endif %}
	{% endfor %}

	{% block page_content %}{% endblock %}
</div>
{% endblock %}

Source Code/Flask/app/templates/index.html
{% extends "header.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
	Midnight Inventers
{% endblock %}

{% block page_content %}
	<div class="page-header">
		<h2 class="h2">
			Midnight Inventers
		</h2>
		<h3 class="h3">
			Web Interface for POX SDN Controller
		</h3>
	</div>

	<h3 class="h3">
		{% if name %}Welcome, {{ name }}!{% else %}Anonymous Session{% endif %}
	</h3>
	
	{% if not name %}	
		{{ wtf.quick_form(form) }}
	{% endif %}
{% endblock %}

Source Code/Flask/app/templates/links.html
{% extends "header.html" %}

{% block title %}
	Links
{% endblock %}

{% block page_content %}
	<div class="page-header">
		<h3 class="h3">
			Topology
		</h3>
	</div>
	<div class="container svg-block">
		<button class="btn btn-success custom-btn">Reload Topology</button>
		<br/><br/>
		<svg width="960" height="500"></svg>
	</div>
	<div class="container legend">
		<h5 class="h5">
			<strong>Legend</strong>
		</h3>
		<table>
			<tr>
				<td>
					<div class="circle-legend green-circle"></div>
				</td>
				<td>
					Switch
				</td>
			</tr>
			<tr>
				<td>
					<div class="circle-legend blue-circle"></div>
				</td>
				<td>
					Host
				</td>
			</tr>
		</table>
	</div>
{% endblock %}

{% block scripts %}
	{{ super() }}
	<script type="text/javascript" src="{{url_for('static', filename='js/links.js')}}"></script>
	<script type="text/javascript" src="{{url_for('static', filename='js/d3.min.js')}}"></script>

	<script type="text/javascript">
		var svg = d3.select("svg");
		var width = +svg.attr("width");
		var height = +svg.attr("height");

		var color = d3.scaleOrdinal()
  							.domain(["1", "2", "3"])
							.range(["#65C400" , "#2290EE", "#000000"]);

		var simulation = d3.forceSimulation().force("link", d3.forceLink().id(function(d) { return d.id; }).distance(60)).force("charge", d3.forceManyBody()).force("center", d3.forceCenter(width / 2, height / 2));

		d3.json("{{url_for('static', filename='json/topo.json')}}", function(error, graph) { 
		if (error) throw error;

		var link = svg.append("g")
					.attr("class", "links")
					.selectAll("line")
					.data(graph.links)
					.enter()
					.append("line")
					.attr("stroke-width", function(d) { 
						return Math.sqrt(d.value); 
					});

		var node = svg.append("g")
					.attr("class", "nodes")
					.selectAll("circle")
					.data(graph.nodes)
					.enter()
					.append("circle")
					.attr("r", 7)
					.attr("fill", function(d) { 
						return color(d.group); 
					})
					.on('dblclick', function(event) {
						connectedNodes(d3.select(this).node().__data__)
					})
					.call(d3.drag()
							.on("start", dragstarted)
							.on("drag", dragged)
							.on("end", dragended)					
					); 

		node.append("title")
			.text(function(d) { 
				return d.id; 
			});

		simulation.nodes(graph.nodes).on("tick", ticked);

		simulation.force("link").links(graph.links);

		function ticked() {
			link.attr("x1", function(d) { 
				return d.source.x; 
			}).attr("y1", function(d) { 
				return d.source.y; 
			}).attr("x2", function(d) { 
				return d.target.x; 
			}).attr("y2", function(d) { 
				return d.target.y; 
			});

			node.attr("cx", function(d) { 
				return d.x; 
			}).attr("cy", function(d) { 
				return d.y; 
			});
		}
		var padding = 1, radius=6;
		function collide(alpha) {
			var quadtree = d3.geom.quadtree(graph.nodes);
			return function(d) {
		    var rb = 2*radius + padding,
		        nx1 = d.x - rb,
		        nx2 = d.x + rb,
		        ny1 = d.y - rb,
		        ny2 = d.y + rb;
		    quadtree.visit(function(quad, x1, y1, x2, y2) {
			if (quad.point && (quad.point !== d)) {
				var x = d.x - quad.point.x,
				y = d.y - quad.point.y,
				l = Math.sqrt(x * x + y * y);
				if (l < rb) {
					l = (l - rb) / l * alpha;
					d.x -= x *= l;
					d.y -= y *= l;
					quad.point.x += x;
					quad.point.y += y;
				}
			}
			return x1 > nx2 || x2 < nx1 || y1 > ny2 || y2 < ny1;
			});
			};
		}
		
		var toggle = 0;
		var linkedByIndex = {};
		for (i = 0; i < graph.nodes.length; i++) {
		    linkedByIndex[i + "," + i] = 1;
		};
		graph.links.forEach(function (d) {
		    linkedByIndex[d.source.index + "," + d.target.index] = 1;
		});
		function neighboring(a, b) {
		    return linkedByIndex[a.index + "," + b.index];
		}
		function connectedNodes(d) {
		    if (toggle == 0) {
		        node.style("opacity", function (o) {
		            return neighboring(d, o) | neighboring(o, d) ? 1 : 0.1;
		        });
		        link.style("opacity", function (o) {
		            return d.index==o.source.index | d.index==o.target.index ? 1 : 0.1;
		        });
		        toggle = 1;
		    } 
		    else {
		        node.style("opacity", 1);
		        link.style("opacity", 1);
		        toggle = 0;
		    }
		}

		force.on("tick", function () {
		    link.attr("x1", function (d) {
		        return d.source.x;
		    }).attr("y1", function (d) {
		        return d.source.y;
		    }).attr("x2", function (d) {
		        return d.target.x;
		    }).attr("y2", function (d) {
		        return d.target.y;
		    });
		    node.attr("cx", function (d) {
		        return d.x;
		    }).attr("cy", function (d) {
		        return d.y;
		    });
		    node.each(collide(0.5));
		});

		});

		function dragstarted(d) {
			if (!d3.event.active) simulation.alphaTarget(0.3).restart();
			d.fx = d.x;
			d.fy = d.y;
		}

		function dragged(d) {
			d.fx = d3.event.x;
			d.fy = d3.event.y;
		}

		function dragended(d) {
			if (!d3.event.active) simulation.alphaTarget(0);
			d.fx = null;
			d.fy = null;
		}
	</script>
{% endblock %}

Source Code/Flask/app/templates/switches.html
{% extends "header.html" %}

{% block title %}
	Switches
{% endblock %}

{% block page_content %}
	<div class="page-header">
		<h3 class="h3">
			List of Switches connected :
		</h3>
	</div>
	<div class="table-responsive">
		<table class="table table-hover">
			{% for line_count in range(resp.__len__()) %}
			<tr>
				<td class="click-dropdown-field">
					<div class="header">
						<strong>
							<span class="device-number">
								Switch {{line_count + 1}} :
							</span>

							<span class="device-address">
								Datapath Address : {{resp[line_count].dpid}}
							</span>
						</strong>
					</div>

					<div class="content-switches">
						Remote IP Address : {{resp[line_count].remoteIp}}
						<br/>
						Port Number : {{resp[line_count].remotePort}}
					</div>
				</td>
			</tr>
			{% endfor %}
		</table>
	</div>
{% endblock %}

{% block scripts %}
	{{ super() }}
	<script type="text/javascript" src="{{url_for('static', filename='js/switches.js')}}"></script>
	<script type="text/javascript">
		setInterval(function(){
			$('.table-responsive').load(document.URL +  ' .table-responsive');
		}, 5000);
	</script>
{% endblock %}

Source Code/Flask/templates/header.html
{% extends "base.html" %}

{% block head %}
{{ super() }}
<link rel="shortcut-icon" type="image/x-icon" href="{{url_for('static', filename='images/image.ico')}}">
<link rel="icon" type="image/x-icon" href="{{url_for('static', filename='images/image.ico')}}">
{% endblock %}

{% block title %}Midnight Inventers{% endblock %}

{% block navbar %}
<nav class="navbar navbar-inverse">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false">
				<span class="sr-only">Toggle Navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{{url_for('index', _external=True)}}">
				<strong>
					Midnight Inventers	
				</strong>
			</a>
		</div>

		{% if name %}
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li>
						<a href="{{url_for('devices', _external=True)}}">
							Devices
						</a>
					</li>
					<li>
						<a href="{{url_for('switches', _external=True)}}">
							Switches
						</a>
					</li>
					<li>
						<a href="{{url_for('links', _external=True)}}">
							Links
						</a>
					</li>
				</ul>

				<ul class="nav navbar-nav navbar-right">
					<li>
						<a href="{{url_for('index', redirect=True)}}">
							<span class="glyphicon glyphicon-log-out"></span>
							<strong>
								Logout
							</strong>
						</a>
					</li>
				</ul>
			</div>
		{% endif %}

	</div>
</nav>
{% endblock %}


{% block content %}
<div class="container">
	{% for category, message in get_flashed_messages(with_categories=true) %}
		{% if category == "success" %}
			<div class="alert alert-success">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				{{ message }}
			</div>
		{% else %}
			<div class="alert alert-danger">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				{{ message }}
			</div>
		{% endif %}
	{% endfor %}

	{% block page_content %}{% endblock %}
</div>
{% endblock %}